language: python
script: make test_long
dist: xenial
sudo: true
matrix:
  exclude:
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.1.*
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
env:
  - MATPLOTLIB_VERSION=1.5.*
  - MATPLOTLIB_VERSION=2.0.*
  - MATPLOTLIB_VERSION=2.1.*
  - MATPLOTLIB_VERSION=2.2.*
  - MATPLOTLIB_VERSION=3.0.* PYQT=PyQt5
  - MATPLOTLIB_VERSION=3.1.* PYQT=PyQt5
addons:
  apt:
    packages:
    - libxkbcommon-x11-0
services:
  - xvfb
install:
  - pip install mock
  - '[ -n "$PYQT" ] && pip install ${PYQT} || true'
  - pip install matplotlib==${MATPLOTLIB_VERSION}
notifications:
  pushover:
    api_key:
      secure: NVBdwHfLX60WsmuZGn8r4R/zBqR8t2eo8RYLBowWKMeUQZSY/9Pg7Esl2LrhSp3dktQJrocc656PXYDBI37C+2kj17c+XGtKMFiUvQACBuOc0088+8Riu91XqjExwP8wH0aEDpmKCzUL6/lGMLse2zuonxClflFFjYL9GPzxom4=
    users:
      secure: Y4NyGJ+vlqp7N1BhyHwQR4JBsEgEvSLOvRD7xxl/BFjnmABZUvwDpnji2owGO0T+pSMua3gYL90k7FZDgCvHROFsumiA4Qq2O6FsxJPGxyoOHXryJzI6Md3FbR5EnC1LNWb9/RRaoaqLWFEEIJE0DxkZZIy3CsFTqaKpYzb4Uf4=
