language: python
script: make test_long
dist: xenial
os: linux
jobs:
  exclude:
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.1.* PYQT=PyQt5
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.1.* PYQT=PySide2
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.2.* PYQT=PyQt5
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.2.* PYQT=PySide2
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.3.* PYQT=PyQt5
    - python: "3.5"
      env: MATPLOTLIB_VERSION=3.3.* PYQT=PySide2
    - python: "3.8"
      env: MATPLOTLIB_VERSION=1.5.*
    - python: "3.8"
      env: MATPLOTLIB_VERSION=2.0.*
    - python: "3.8"
      env: MATPLOTLIB_VERSION=2.1.*
    - python: "3.8"
      env: MATPLOTLIB_VERSION=2.2.*
    - python: "3.9"
      env: MATPLOTLIB_VERSION=1.5.*
    - python: "3.9"
      env: MATPLOTLIB_VERSION=2.0.*
    - python: "3.9"
      env: MATPLOTLIB_VERSION=2.1.*
    - python: "3.9"
      env: MATPLOTLIB_VERSION=2.2.*
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - MATPLOTLIB_VERSION=1.5.*
  - MATPLOTLIB_VERSION=2.0.*
  - MATPLOTLIB_VERSION=2.1.*
  - MATPLOTLIB_VERSION=2.2.*
  - MATPLOTLIB_VERSION=3.0.* PYQT=PyQt5
  - MATPLOTLIB_VERSION=3.0.* PYQT=PySide2
  - MATPLOTLIB_VERSION=3.1.* PYQT=PyQt5
  - MATPLOTLIB_VERSION=3.1.* PYQT=PySide2
  - MATPLOTLIB_VERSION=3.2.* PYQT=PyQt5
  - MATPLOTLIB_VERSION=3.2.* PYQT=PySide2
  - MATPLOTLIB_VERSION=3.3.* PYQT=PyQt5
  - MATPLOTLIB_VERSION=3.3.* PYQT=PySide2
addons:
  apt:
    packages:
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-render0
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-sync1
    - libxcb-util1
    - libxcb-xfixes0
    - libxcb-xinerama0
    - libxcb-xkb1
    - libxkbcommon-x11-0
services:
  - xvfb
install:
  - pip install mock
  - '[ -n "$PYQT" ] && pip install QtPy ${PYQT} || true'
  - pip install matplotlib==${MATPLOTLIB_VERSION}
notifications:
  pushover:
    api_key:
      secure: NVBdwHfLX60WsmuZGn8r4R/zBqR8t2eo8RYLBowWKMeUQZSY/9Pg7Esl2LrhSp3dktQJrocc656PXYDBI37C+2kj17c+XGtKMFiUvQACBuOc0088+8Riu91XqjExwP8wH0aEDpmKCzUL6/lGMLse2zuonxClflFFjYL9GPzxom4=
    users:
      secure: Y4NyGJ+vlqp7N1BhyHwQR4JBsEgEvSLOvRD7xxl/BFjnmABZUvwDpnji2owGO0T+pSMua3gYL90k7FZDgCvHROFsumiA4Qq2O6FsxJPGxyoOHXryJzI6Md3FbR5EnC1LNWb9/RRaoaqLWFEEIJE0DxkZZIy3CsFTqaKpYzb4Uf4=
